#ifndef _FSL_DEBUG_CONSOLE_CONF_H_
#define _FSL_DEBUG_CONSOLE_CONF_H_

#define DEBUG_CONSOLE_TRANSFER_NON_BLOCKING 0U
#define DEBUG_CONSOLE_RX_ENABLE 0U
#define DEBUG_CONSOLE_ENABLE_ECHO 0U
#define DEBUG_CONSOLE_BUFFER_SIZE 128U

#endif